name: Deployment
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: NyCodeGHG/wrangler-action@1.3.0-fix
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
